// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineTesting.Infrastructure.Persistence;

#nullable disable

namespace OnlineTesting.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529235227_AddUserName")]
    partial class AddUserName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnlineTesting.Domain.Payments.ClickTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ClickTransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("click_transaction_id");

                    b.Property<DateTime?>("CompleteTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("complete_time");

                    b.Property<int>("Error")
                        .HasColumnType("integer")
                        .HasColumnName("error");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<long>("PrepareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("prepare_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("PrepareId"));

                    b.Property<DateTime>("PrepareTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prepare_time");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_click_transactions");

                    b.HasIndex("ClickTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_click_transactions_click_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_click_transactions_order_id");

                    b.HasIndex("PrepareId")
                        .IsUnique()
                        .HasDatabaseName("ux_click_transactions_prepare_id");

                    b.ToTable("click_transactions", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Payments.PaymeTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<int?>("CancelReason")
                        .HasColumnType("integer")
                        .HasColumnName("cancel_reason");

                    b.Property<long?>("CancelTime")
                        .HasColumnType("bigint")
                        .HasColumnName("cancel_time");

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("create_time");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymeTransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payme_transaction_id");

                    b.Property<long?>("PerformTime")
                        .HasColumnType("bigint")
                        .HasColumnName("perform_time");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_payme_transactions");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payme_transactions_order_id");

                    b.HasIndex("PaymeTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_payme_transactions_payme_id");

                    b.ToTable("payme_transactions", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Payments.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountTiyin")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_tiyin");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_orders");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_payment_orders_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payment_orders_user_id");

                    b.ToTable("payment_orders", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Progress.UserDailyActivity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("ActivityDate")
                        .HasColumnType("date")
                        .HasColumnName("activity_date");

                    b.HasKey("UserId", "ActivityDate")
                        .HasName("pk_user_daily_activities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_daily_activities_user_id");

                    b.ToTable("user_daily_activities", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_subscriptions_expires_at");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_user_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Subscriptions.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_subscription_plans");

                    b.HasIndex("Type", "Duration")
                        .IsUnique()
                        .HasDatabaseName("ux_subscription_plans_type_duration");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Teacher.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("invite_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ux_groups_invite_code");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_groups_teacher_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Teacher.GroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("GroupId", "UserId")
                        .HasName("pk_group_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_members_user_id");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Teacher.TeacherApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("text")
                        .HasColumnName("additional_notes");

                    b.Property<string>("ExperienceText")
                        .HasColumnType("text")
                        .HasColumnName("experience_text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("organization_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("telegram_username");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_teacher_applications");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_teacher_applications_status");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_teacher_applications_user_pending")
                        .HasFilter("status = 0");

                    b.ToTable("teacher_applications", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Teacher.TestLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BiletId")
                        .HasColumnType("uuid")
                        .HasColumnName("bilet_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FlowType")
                        .HasColumnType("integer")
                        .HasColumnName("flow_type");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<int?>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<List<Guid>>("TopicIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("topic_ids");

                    b.HasKey("Id")
                        .HasName("pk_test_links");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_test_links_code");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_test_links_teacher_id");

                    b.ToTable("test_links", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_answers_question_id");

                    b.HasIndex("QuestionId", "IsCorrect")
                        .IsUnique()
                        .HasDatabaseName("ux_answers_question_correct")
                        .HasFilter("is_correct = true");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.AnswerTranslation", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("answer_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language_code");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("AnswerId", "LanguageCode")
                        .HasName("pk_answer_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_answer_translations_language_code");

                    b.ToTable("answer_translations", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BiletId")
                        .HasColumnType("uuid")
                        .HasColumnName("bilet_id");

                    b.Property<int?>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Flow")
                        .HasColumnType("integer")
                        .HasColumnName("flow_type");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TestLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_link_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_attempts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_attempts_user_id");

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.AttemptQuestion", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid?>("ChosenAnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("chosen_answer_id");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.HasKey("AttemptId", "QuestionId")
                        .HasName("pk_attempt_questions");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_attempt_questions_question_id");

                    b.ToTable("attempt_questions", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Bilet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bilets");

                    b.HasIndex("IsDemo")
                        .IsUnique()
                        .HasDatabaseName("ux_bilets_demo")
                        .HasFilter("is_demo = true");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_bilets_number");

                    b.ToTable("bilets", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.BiletQuestion", b =>
                {
                    b.Property<Guid>("BiletId")
                        .HasColumnType("uuid")
                        .HasColumnName("bilet_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.HasKey("BiletId", "QuestionId")
                        .HasName("pk_bilet_questions");

                    b.HasIndex("QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_bilet_questions_question");

                    b.HasIndex("BiletId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_bilet_questions_order");

                    b.ToTable("bilet_questions", null, t =>
                        {
                            t.HasCheckConstraint("ck_bilet_questions_order_range", "order_index BETWEEN 1 AND 20");
                        });
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.HasKey("Code")
                        .HasName("pk_languages");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_languages_default")
                        .HasFilter("is_default = true");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_questions_topic_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.QuestionTranslation", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language_code");

                    b.Property<string>("Explanation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("explanation");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("QuestionId", "LanguageCode")
                        .HasName("pk_question_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_question_translations_language_code");

                    b.ToTable("question_translations", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_topics");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_topics_code");

                    b.HasIndex("IsDemo")
                        .IsUnique()
                        .HasDatabaseName("ux_topics_demo")
                        .HasFilter("is_demo = true");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.TopicTranslation", b =>
                {
                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("TopicId", "LanguageCode")
                        .HasName("pk_topic_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_topic_translations_language_code");

                    b.ToTable("topic_translations", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Users.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_user_id");

                    b.Property<string>("ExternalUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_username");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_logins");

                    b.HasIndex("Provider", "ExternalUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_logins_provider_external_user_id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_external_logins_user_id_provider");

                    b.ToTable("external_logins", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OnlineTesting.Domain.Teacher.GroupMember", b =>
                {
                    b.HasOne("OnlineTesting.Domain.Teacher.Group", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Answer", b =>
                {
                    b.HasOne("OnlineTesting.Domain.Tests.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_questions_question_id");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.AnswerTranslation", b =>
                {
                    b.HasOne("OnlineTesting.Domain.Tests.Answer", null)
                        .WithMany("Translations")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answer_translations_answers_answer_id");

                    b.HasOne("OnlineTesting.Domain.Tests.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_answer_translations_languages_language_code");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.AttemptQuestion", b =>
                {
                    b.HasOne("OnlineTesting.Domain.Tests.Attempt", "Attempt")
                        .WithMany("Questions")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_questions_attempts_attempt_id");

                    b.HasOne("OnlineTesting.Domain.Tests.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_questions_questions_question_id");

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.BiletQuestion", b =>
                {
                    b.HasOne("OnlineTesting.Domain.Tests.Bilet", "Bilet")
                        .WithMany("BiletQuestions")
                        .HasForeignKey("BiletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bilet_questions_bilets_bilet_id");

                    b.HasOne("OnlineTesting.Domain.Tests.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bilet_questions_questions_question_id");

                    b.Navigation("Bilet");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Question", b =>
                {
                    b.HasOne("OnlineTesting.Domain.Tests.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_questions_topics_topic_id");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.QuestionTranslation", b =>
                {
                    b.HasOne("OnlineTesting.Domain.Tests.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_question_translations_languages_language_code");

                    b.HasOne("OnlineTesting.Domain.Tests.Question", null)
                        .WithMany("Translations")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_translations_questions_question_id");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.TopicTranslation", b =>
                {
                    b.HasOne("OnlineTesting.Domain.Tests.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_topic_translations_languages_language_code");

                    b.HasOne("OnlineTesting.Domain.Tests.Topic", null)
                        .WithMany("Translations")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topic_translations_topics_topic_id");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Users.ExternalLogin", b =>
                {
                    b.HasOne("OnlineTesting.Domain.Users.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_logins_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("OnlineTesting.Domain.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Teacher.Group", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Answer", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Attempt", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Bilet", b =>
                {
                    b.Navigation("BiletQuestions");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Tests.Topic", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("OnlineTesting.Domain.Users.User", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
